@Host = http://localhost:5500/api/v1
@ContentType = application/json 

POST {{Host}}/auth/signup
Content-Type: {{ContentType}}

{
    "username":"test1",
    "password":"test123",
    "confirmPassword": "test123",
    "firstName":"Test",
    "lastName":"One"
}

###

POST {{Host}}/auth/signin
Content-Type: {{ContentType}}
authType: JWT

{
    "username":"test1",
    "password":"test123"
}